title: Alex MacLean
email: alex@alex-maclean.com
description: >-
  The personal website for Alex MacLean of Seattle, Washington.

baseurl: ""
url: "https://alex-maclean.com"

plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - node_modules
  - package.json
  - package-lock.json
  - src
  - tsconfig.json
